2017-01-29 08:31:29,868 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-29 13:00:48,924 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-29 13:03:30,315 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
