2017-01-07 08:11:13,125 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Vienna state: VA zipcode: 22182 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/22182/sold?min_bed=1 bed: 4 home_price: 680000.0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-07 08:11:13,362 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Vienna state: VA zipcode: 22182 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/22182/sold?min_bed=1 bed: 4 home_price: 680000.0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-07 08:21:43,884 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-08 10:11:57,328 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-09 18:26:17,240 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-10 18:30:52,585 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-11 21:54:16,493 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-12 18:00:23,276 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 75, in <module>
    today_file_format = datetime.datetime.strptime(today_file, '%Y-%m-%d').date()
  File "C:\Python27\lib\_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '0.959' does not match format '%Y-%m-%d'
2017-01-13 22:51:44,786 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Chantilly state: VA zipcode: 20151 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/20151/sold?min_bed=1 bed: 1 home_price: 225900.0
Traceback (most recent call last):
  File "home_estately.py", line 208, in <module>
    b = requests.get(property_url)
  File "C:\Python27\lib\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 476, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 597, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.estately.com', port=80): Max retries exceeded with url: /listings/info/3850-lightfoot-street--23 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03CBF6B0>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
2017-01-14 00:51:22,433 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Vienna state: VA zipcode: 22182 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/22182/sold?min_bed=1 bed: 4 home_price: 840000.0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-14 04:02:21,489 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: Reston state: VA zipcode: 20190 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/VA/20190/sold?min_bed=1 bed: 2 home_price: 743000.0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-14 07:16:47,390 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: miami neigh:  city: Miami state: FL zipcode: 33167 url: 0 bedroom_no: 0 craigs_price: 0 estate_url: http://www.estately.com/FL/33167/sold?min_bed=1 bed: 2 home_price: 59000.0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-15 06:56:13,930 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-16 08:35:13,029 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-17 08:58:18,676 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-18 19:14:55,180 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-19 03:00:33,082 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-01-20 06:53:39,788 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "home_estately.py", line 64, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
