2017-02-05 11:18:01,451 - __main__ - ERROR - 0
Traceback (most recent call last):
  File "miami_rent.py", line 50, in <module>
    for row in csv_reader:
Error: line contains NULL byte
2017-02-05 11:40:10,190 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: miami neigh:  city: Miami state: FL zipcode: 33160 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "miami_rent.py", line 52, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 02:19:00,229 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: washingtondc neigh:  city: College Park state: MD zipcode: 20740 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\washingtondc_rent.py", line 110, in <module>
    r_h = requests.get(url_h)
  File "C:\Python27\lib\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 476, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 597, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\requests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host="01-31'.craigslist.org", port=80): Max retries exceeded with url: /search/apa?s=0&bedrooms=1&query=-130+%22house%22+-%22townhouse%22+-%22town+house%22+-%22town+home%22+-%22condo%22+-+%22condominium%22+-%22apartment%22&sort=date (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03AF7B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2017-02-06 02:33:41,934 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: miami neigh:  city: Miami state: FL zipcode: 33160 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\miami_rent.py", line 52, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 02:41:31,434 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: richmond neigh:  city: Richmond state: VA zipcode: 23291 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\richmond_rent.py", line 52, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 02:49:14,957 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: sanfrancisco neigh:  city: San Francisco state: CA zipcode: 94163 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\sf_rent.py", line 52, in <module>
    craigs_url = cities_states[line][column]
IndexError: list index out of range
2017-02-06 02:54:55,792 - __main__ - ERROR - %(asctime)s %(message)s craigs_url: baltimore neigh:  city: Baltimore state: MD zipcode: 21239 url: 0 bedroom_no: 0 craigs_price: 0
Traceback (most recent call last):
  File "C:\Users\Gian Bustillo\Desktop\RealEstateProject\real-estate\baltimore_rent.py", line 110, in <module>
    r_h = requests.get(url_h)
  File "C:\Python27\lib\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\requests\sessions.py", line 462, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\requests\sessions.py", line 395, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\requests\models.py", line 299, in prepare
    self.prepare_url(url, params)
  File "C:\Python27\lib\requests\models.py", line 368, in prepare_url
    raise InvalidURL('URL has an invalid label.')
InvalidURL: URL has an invalid label.
